cors:
  global:
    origins: >
      https://marketplace.demo.merlot-education.eu,
      https://api.demo.merlot-education.eu,
      https://cif.demo.merlot-education.eu
    patterns:

spring:
  h2:
    console.enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth-service.demo.merlot-education.eu
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/oauth2/jwks
          userinfo-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/userinfo


jwt-auth-converter: ssiJwtAuthConverter

merlot-domain: "marketplace.demo.merlot-education.eu"

gxfscatalog-library:
  ignore-ssl: false

init-data:
  ocm-agent-did: "UaT2udeT53Tr1n6itV46Z"
  gxdch-delay: 20000

db:
  encryption:
    key: ""

daps-server:
  base-uri: http://daps-server.merlot.svc.cluster.local:4567

gxdch-services:
  enforce-compliance: true
  enforce-notary: true
  compliance-base-uris:
    "https://compliance.lab.gaia-x.eu/v1-staging" #,
    #"https://gx-compliance.aruba.it",
  #"https://gx-compliance.gxdch.dih.telekom.com",
  #"https://gx-compliance.airenetworks.es"
  registry-base-uris:
    "https://registry.lab.gaia-x.eu/v1-staging" #,
    #"https://gx-registry.aruba.it",
  #"https://gx-registry.gxdch.dih.telekom.com",
  #"https://gx-registry.airenetworks.es"
  notary-base-uris:
    "https://registrationnumber.notary.lab.gaia-x.eu/v1-staging" #,
    #"https://gx-notary.aruba.it",
  #"https://gx-notary.gxdch.dih.telekom.com",
  #"https://gx-notary.airenetworks.es"
