#  Copyright 2023-2024 Dataport AöR
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

cors:
  global:
    origins: >
      https://marketplace.demo.merlot-education.eu,
      https://api.demo.merlot-education.eu,
      https://cif.demo.merlot-education.eu,
      https://occ.dev.merlot-education.eu
    patterns:

spring:
  h2:
    console.enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth-service.demo.merlot-education.eu
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/oauth2/jwks
          userinfo-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/userinfo


jwt-auth-converter: ssiJwtAuthConverter

merlot-domain: "marketplace.demo.merlot-education.eu"
merlot-federation-did: "did:web:marketplace.demo.merlot-education.eu:participant:df15587a-0760-32b5-9c42-bb7be66e8076"

gxfscatalog-library:
  ignore-ssl: false

init-data:
  ocm-agent-did: "UaT2udeT53Tr1n6itV46Z"
  gxdch-delay: 20000

db:
  encryption:
    key: ""

daps-server:
  base-uri: http://daps-server.merlot.svc.cluster.local:4567

gxdch-services:
  enforce-compliance: true
  enforce-notary: true
  compliance-base-uris:
    "https://compliance.lab.gaia-x.eu/v1-staging" #,
    #"https://gx-compliance.aruba.it",
  #"https://gx-compliance.gxdch.dih.telekom.com",
  #"https://gx-compliance.airenetworks.es"
  registry-base-uris:
    "https://registry.lab.gaia-x.eu/v1-staging" #,
    #"https://gx-registry.aruba.it",
  #"https://gx-registry.gxdch.dih.telekom.com",
  #"https://gx-registry.airenetworks.es"
  notary-base-uris:
    "https://registrationnumber.notary.lab.gaia-x.eu/v1-staging" #,
    #"https://gx-notary.aruba.it",
  #"https://gx-notary.gxdch.dih.telekom.com",
  #"https://gx-notary.airenetworks.es"
