cors:
  global:
    origins: >
      https://marketplace.dev.merlot-education.eu,
      https://api.dev.merlot-education.eu,
      https://cif.dev.merlot-education.eu
    patterns:

spring:
  h2:
    console.enabled: false

merlot-domain: "marketplace.dev.merlot-education.eu"

gxfscatalog-library:
  ignore-ssl: false

db:
  encryption:
    key: ""

daps-connector-api:
  base-uri: http://daps-server.merlot.svc.cluster.local:4567/api/v1/connectors