logging:
  level:
    org.springframework.security: DEBUG

spring:
  profiles:
    active: default
  datasource:
    url: jdbc:h2:file:./database.db
    username: sa
    password:
    driverClassName: org.h2.Driver
    initialization-mode: always
  jackson:
    mapper:
      DEFAULT_VIEW_INCLUSION: true
  jpa:
    generate-ddl: true
    ddl:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: true
        format_sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    connection-timeout: 30000
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true
  servlet:
    multipart:
      max-file-size: 2MB

server:
  port: '8082'
  servlet:
    context-path: /api
  error:
    include-stacktrace: "never"

gxfscatalog:
  base-uri: "http://localhost:8081"
  participants-uri: "${gxfscatalog.base-uri}/participants"
  selfdescriptions-uri: "${gxfscatalog.base-uri}/self-descriptions"
  query-uri: "${gxfscatalog.base-uri}/query"
  private-key-path: ""
  cert-path: ""
  verification-method: "did:web:compliance.lab.gaia-x.eu"

gxfswizardapi:
  base-uri: "http://localhost:8085"

management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: "/"
  endpoint:
    health:
      enabled: true

keycloak:
  client-id: "federated-catalogue"
  authorization-grant-type: "password"
  base-uri: "http://key-server:8080"
  oidc-base-uri: "${keycloak.base-uri}/realms/gxfscatalog/protocol/openid-connect"
  token-uri: "${keycloak.oidc-base-uri}/token"
  logout-uri: "${keycloak.oidc-base-uri}/logout"
  client-secret: "CScowEqRGIb6d7SLCZHVjKHIewp0ZmnO"
  gxfscatalog-user: "gxfscatalog"
  gxfscatalog-pass: "gxfscatalog"

init-data:
  organisations: "classpath:organisations/"
  connectors: "classpath:initial-orga-connectors.json"

merlot-domain: "localhost"

db:
  encryption:
    key: "1234123412341234"

cors:
  global:
    origins:
    patterns: >
      http://localhost:[*]

gxfscatalog-library:
  ignore-ssl: true