cors:
  global:
    origins: >
      https://marketplace.demo.merlot-education.eu,
      https://api.demo.merlot-education.eu,
      https://cif.demo.merlot-education.eu
    patterns:

spring:
  h2:
    console.enabled: false

merlot-domain: "marketplace.demo.merlot-education.eu"

gxfscatalog-library:
  ignore-ssl: false

db:
  encryption:
    key: ""

daps-server:
  base-uri: http://daps-server.merlot.svc.cluster.local:4567