logging:
  level:
    org.springframework.security: DEBUG

spring:
  profiles:
    active: default
  datasource:
    url: jdbc:h2:file:./database.db
    username: sa
    password:
    driverClassName: org.h2.Driver
    initialization-mode: always
  jackson:
    mapper:
      DEFAULT_VIEW_INCLUSION: true
  jpa:
    generate-ddl: true
    ddl:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: true
        format_sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true
  servlet:
    multipart:
      max-file-size: 2MB

server:
  port: '8082'
  servlet:
    context-path: /api
  error:
    include-stacktrace: "never"

gxfscatalog:
  base-uri: "http://localhost:8081"
  participants-uri: "${gxfscatalog.base-uri}/participants"
  selfdescriptions-uri: "${gxfscatalog.base-uri}/self-descriptions"
  query-uri: "${gxfscatalog.base-uri}/query"
  private-key-path: "${user.home}/workspace/mpo/merlot-cert/prk.ss.pem"
  cert-path: "${user.home}/workspace/mpo/merlot-cert/cert.ss.pem"
  verification-method: "did:web:merlot-education.eu"

gxfswizardapi:
  base-uri: "http://localhost:8085"

management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: "/"
  endpoint:
    health:
      enabled: true

keycloak:
  client-id: "federated-catalogue"
  authorization-grant-type: "password"
  base-uri: "http://key-server:8080"
  oidc-base-uri: "${keycloak.base-uri}/realms/gxfscatalog/protocol/openid-connect"
  token-uri: "${keycloak.oidc-base-uri}/token"
  logout-uri: "${keycloak.oidc-base-uri}/logout"
  client-secret: "oV0GOkc0XWUoDwNV38qjqWfri6Uk7tTQ"
  gxfscatalog-user: "gxfscatalog"
  gxfscatalog-pass: "gxfscatalog"

edc-tokens:
  edc1: "somevalue"
  edc2: "somevalue"

init-data:
  organisations: "${user.home}/workspace/mpo/initial-orgas.json"
  connectors: "${user.home}/workspace/mpo/initial-orga-connectors.json"

merlot-domain: "marketplace.dev.merlot-education.eu"