cors:
  global:
    origins: >
      https://marketplace.demo.merlot-education.eu,
      https://api.demo.merlot-education.eu,
      https://cif.demo.merlot-education.eu
    patterns:

spring:
  h2:
    console.enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth-service.demo.merlot-education.eu
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/oauth2/jwks
          userinfo-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/userinfo


jwt-auth-converter: ssiJwtAuthConverter

merlot-domain: "marketplace.demo.merlot-education.eu"

gxfscatalog-library:
  ignore-ssl: false

db:
  encryption:
    key: ""

daps-server:
  base-uri: http://daps-server.merlot.svc.cluster.local:4567